"""empty message

Revision ID: 1bd3ceaa39d8
Revises: 8d8fabacfdaf
Create Date: 2021-02-02 23:19:25.490208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bd3ceaa39d8'
down_revision = '8d8fabacfdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_company',
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='association_company_ibfk_2'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='association_company_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
