"""empty message

Revision ID: 4189325b0d4d
Revises: e105b92b5c32
Create Date: 2021-01-18 11:04:47.865968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4189325b0d4d'
down_revision = 'e105b92b5c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name_company', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'name_company')
    # ### end Alembic commands ###
