"""empty message

Revision ID: 763f7ff2e172
Revises: 2d97366842b7
Create Date: 2021-02-04 20:02:24.757073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763f7ff2e172'
down_revision = '2d97366842b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name_agro', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('phone_agro', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'phone_agro')
    op.drop_column('company', 'name_agro')
    # ### end Alembic commands ###
