"""empty message

Revision ID: 8d8fabacfdaf
Revises: dda1d5bcc743
Create Date: 2021-02-02 20:33:22.299006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8fabacfdaf'
down_revision = 'dda1d5bcc743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'company_id')
    # ### end Alembic commands ###
