"""empty message

Revision ID: dda1d5bcc743
Revises: 4189325b0d4d
Create Date: 2021-01-18 11:13:49.758360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda1d5bcc743'
down_revision = '4189325b0d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('edit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'edit_time')
    op.drop_column('company', 'create_time')
    # ### end Alembic commands ###
